In [17]:
import os
import pandas as pd

In [27]:
###COUNTRY DF

In [19]:
country_txt_direct = r"C:\Users\PEREZRT\Documents\Country"

country_songs = []

In [21]:
# Loop through all .txt files in the directory

for songname in os.listdir(country_txt_direct):
    if songname.endswith('.txt'):  # Process only .txt files
        file_path = os.path.join(country_txt_direct, songname)
        
        # Open the file and read its lines
        with open(file_path, 'r') as file:
            lines = file.readlines()  # Read all lines in the file
            
            # For each line, add it as a new row in the list, with the file name as additional info
            for line in lines:
               country_songs.append({'text': line.strip(), 'filename': songname})

In [23]:
countrydf = pd.DataFrame(country_songs)

In [25]:
countrydf

                            text               filename
0              Tennessee Whiskey          BlueGrass.txt
1                      Fire Away          BlueGrass.txt
2                  Starting Over          BlueGrass.txt
3      You Should Probably Leave          BlueGrass.txt
4                           Cold          BlueGrass.txt
..                           ...                    ...
158            Green Green Grass  Singer Songwriter.txt
159                      Runaway  Singer Songwriter.txt
160      Running With The Wolves  Singer Songwriter.txt
161  Murder Song (5, 4, 3, 2, 1)  Singer Songwriter.txt
162           Let Me Down Slowly  Singer Songwriter.txt

[163 rows x 2 columns]

#RAP DF

In [29]:
rap_txt_direct = r"C:\Users\PEREZRT\Documents\Rap"

rap_songs = []

# Loop through all .txt files in the directory

for songname in os.listdir(rap_txt_direct):
    if songname.endswith('.txt'):  # Process only .txt files
        file_path = os.path.join(rap_txt_direct, songname)
        
        # Open the file and read its lines
        with open(file_path, 'r') as file:
            lines = file.readlines()  # Read all lines in the file
            
            # For each line, add it as a new row in the list, with the file name as additional info
            for line in lines:
               rap_songs.append({'text': line.strip(), 'filename': songname})

In [31]:
rapdf = pd.DataFrame(rap_songs)

In [33]:
rapdf

                      text         filename
0    Old Town Road (Remix)  Country Rap.txt
1                Starlight        Grime.txt
2                 Shutdown        Grime.txt
3        Bullet from a Gun        Grime.txt
4              Greaze Mode        Grime.txt
..                     ...              ...
415      beibs in the trap         Trap.txt
416                  90210         Trap.txt
417               YOSEMITE         Trap.txt
418  STOP TRYING TO BE GOD         Trap.txt
419          Never Lose Me         Trap.txt

[420 rows x 2 columns]

In [ ]:
#Rock DF

In [37]:
rock_txt_direct = r"C:\Users\PEREZRT\Documents\Rock"

rock_songs = []

# Loop through all .txt files in the directory

for songname in os.listdir(rock_txt_direct):
    if songname.endswith('.txt'):  # Process only .txt files
        file_path = os.path.join(rock_txt_direct, songname)
        
        # Open the file and read its lines
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
            lines = file.readlines()  # Read all lines in the file
            
            # For each line, add it as a new row in the list, with the file name as additional info
            for line in lines:
               rock_songs.append({'text': line.strip(), 'filename': songname})

In [39]:
rockdf = pd.DataFrame(rock_songs)

In [41]:
rockdf

                           text               filename
0                    Chop Suey!  Alternative Metal.txt
1                      Toxicity  Alternative Metal.txt
2                      B.Y.O.B.  Alternative Metal.txt
3                         Sugar  Alternative Metal.txt
4                    Lonely Day  Alternative Metal.txt
...                         ...                    ...
1208                       Fuel       Thrash Metal.txt
1209     ...And Justice for All       Thrash Metal.txt
1210  Welcome Home (Sanitarium)       Thrash Metal.txt
1211                  Blackened       Thrash Metal.txt
1212        Wherever I May Roam       Thrash Metal.txt

[1213 rows x 2 columns]

In [ ]:
#EDM DF

In [43]:
edm_txt_direct = r"C:\Users\PEREZRT\Documents\EDM"

edm_songs = []

# Loop through all .txt files in the directory

for songname in os.listdir(edm_txt_direct):
    if songname.endswith('.txt'):  # Process only .txt files
        file_path = os.path.join(edm_txt_direct, songname)
        
        # Open the file and read its lines
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
            lines = file.readlines()  # Read all lines in the file
            
            # For each line, add it as a new row in the list, with the file name as additional info
            for line in lines:
               edm_songs.append({'text': line.strip(), 'filename': songname})

In [45]:
edmdf = pd.DataFrame(edm_songs)

In [47]:
edmdf

                   text       filename
0                Flames      Dance.txt
1              One Kiss      Dance.txt
2               Silence      Dance.txt
3    Everybody Hates Me      Dance.txt
4               Lean On      Dance.txt
..                  ...            ...
334             Sexodus  UK Garage.txt
335         Come Around  UK Garage.txt
336                XXXO  UK Garage.txt
337   Come Walk With Me  UK Garage.txt
338      Bucky Done Gun  UK Garage.txt

[339 rows x 2 columns]

In [57]:
#RnB DF

In [59]:
rnb_txt_direct = r"C:\Users\PEREZRT\Documents\RNB"

rnb_songs = []

# Loop through all .txt files in the directory

for songname in os.listdir(rnb_txt_direct):
    if songname.endswith('.txt'):  # Process only .txt files
        file_path = os.path.join(rnb_txt_direct, songname)
        
        # Open the file and read its lines
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
            lines = file.readlines()  # Read all lines in the file
            
            # For each line, add it as a new row in the list, with the file name as additional info
            for line in lines:
               rnb_songs.append({'text': line.strip(), 'filename': songname})

In [61]:
rnbdf = pd.DataFrame(rnb_songs)

In [63]:
rnbdf

                       text  filename
0                 Get Lucky  Funk.txt
1    Lose Yourself to Dance  Funk.txt
2          I Want Your Love  Funk.txt
3           Everybody Dance  Funk.txt
4                Good Times  Funk.txt
..                      ...       ...
349                    Lady  Soul.txt
350    Love Will Find a Way  Soul.txt
351      Come On And See Me  Soul.txt
352   Hold Me Oh My Darling  Soul.txt
353   What A Good Man He Is  Soul.txt

[354 rows x 2 columns]

In [65]:
#Pop DF

In [67]:
pop_txt_direct = r"C:\Users\PEREZRT\Documents\Pop"

pop_songs = []

# Loop through all .txt files in the directory

for songname in os.listdir(pop_txt_direct):
    if songname.endswith('.txt'):  # Process only .txt files
        file_path = os.path.join(pop_txt_direct, songname)
        
        # Open the file and read its lines
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
            lines = file.readlines()  # Read all lines in the file
            
            # For each line, add it as a new row in the list, with the file name as additional info
            for line in lines:
               pop_songs.append({'text': line.strip(), 'filename': songname})

In [69]:
popdf = pd.DataFrame(pop_songs)

In [71]:
popdf

                   text                 filename
0              3 Nights  Alternative Hip-Hop.txt
1           Truth Hurts  Alternative Hip-Hop.txt
2                 Juice  Alternative Hip-Hop.txt
3          Good As Hell  Alternative Hip-Hop.txt
4       About Damn Time  Alternative Hip-Hop.txt
..                  ...                      ...
942  Just the Two of Us                  Pop.txt
943         Mr. Niceguy                  Pop.txt
944              Switch                  Pop.txt
945             Will 2K                  Pop.txt
946             Essence                  Pop.txt

[947 rows x 2 columns]